# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../download-strategy.rb"
class BridgeVpnCli < Formula
  desc "CLI Utility for connecting to the Bridge VPN"
  homepage "https://github.com/instructure-bridge/bridge-vpn-cli"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/instructure-bridge/bridge-vpn-cli/releases/download/v0.1.0/bridge-vpn-cli_0.1.0_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "98c40e77484a70036f0afa9199a755d50738779f4ecf25c1473f9565ae448047"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/instructure-bridge/bridge-vpn-cli/releases/download/v0.1.0/bridge-vpn-cli_0.1.0_Linux_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "a673d6a99b47f03064a18b252cb305cdea2951e633492a04acceffe3f0698771"
    end
  end
  
  depends_on "sshuttle"
  depends_on "openconnect"

  def install
    system "cp", "bridge-vpn-cli", "bridge-vpn"
    bin.install "bridge-vpn"
  end

  test do
    system bin/"bridge-vpn", "help"
  end
end
