# This file was generated by GoReleaser. DO NOT EDIT.
class HomebrewBridgeVpnCli < Formula
  desc ""
  homepage ""
  version "0.1.0-rc1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/instructure-bridge/bridge-vpn-cli/releases/download/v0.1.0-rc1/bridge-vpn-cli_0.1.0-rc1_Darwin_x86_64.tar.gz"
    sha256 "5f772832626010698335881414f0e02b16f3523b6dd8b2173ddbe93a9fb833da"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/instructure-bridge/bridge-vpn-cli/releases/download/v0.1.0-rc1/bridge-vpn-cli_0.1.0-rc1_Linux_x86_64.tar.gz"
      sha256 "57b3f9cecc0753f69b8bc32e2d71801c7c1973816728ec653c05788fb4ac93b7"
    end
  end
  
  depends_on "sshuttle"
  depends_on "openconnect"

  def install
    system "cp", "bridge-vpn-cli", "bvpn"
    bin.install "bvpn"
  end

  test do
    system bin/"bvpn", "help"
  end
end
