# This file was generated by GoReleaser. DO NOT EDIT.
class HomebrewBridgeVpnCli < Formula
  desc ""
  homepage ""
  version "0.1.0-rc2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/instructure-bridge/bridge-vpn-cli/releases/download/v0.1.0-rc2/bridge-vpn-cli_0.1.0-rc2_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "18705311c262edf9d4c9f822fc06e42bce64c53dff650c8a003868e681402177"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/instructure-bridge/bridge-vpn-cli/releases/download/v0.1.0-rc2/bridge-vpn-cli_0.1.0-rc2_Linux_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "2a799c3705278b88e3291309d774a98ef4bbf01d516ded38c21b3ae543d259cb"
    end
  end
  
  depends_on "sshuttle"
  depends_on "openconnect"

  def install
    system "cp", "bridge-vpn-cli", "bvpn"
    bin.install "bvpn"
  end

  test do
    system bin/"bvpn", "help"
  end
end
