# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../download-strategy.rb"
class TrussLocal < Formula
  desc "CLI for running a Local Kubernetes Cluster"
  homepage "https://github.com/get-bridge/truss-local"
  version "0.0.18"

  depends_on "pulumi"
  depends_on "k3d"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/get-bridge/truss-local/releases/download/v0.0.18/truss-local-v0.0.18-darwin-arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "9481f40faf5b7d589195d21e3f09580957ebf7f9c2f088c7e0f3cbfaa09f0a77"

      def install
        bin.install "truss-local"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/get-bridge/truss-local/releases/download/v0.0.18/truss-local-v0.0.18-darwin-amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "70c0d241aa00949337dd8b06ba91f61c7ff18fbfdcc662c6b50e4269edc8e6fc"

      def install
        bin.install "truss-local"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/get-bridge/truss-local/releases/download/v0.0.18/truss-local-v0.0.18-linux-arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "a78e272e069569e24bf8c20503407c19140907fc2d0e09d13d200e76d098ac3a"

      def install
        bin.install "truss-local"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/get-bridge/truss-local/releases/download/v0.0.18/truss-local-v0.0.18-linux-amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "5dcfd098c114c8a8aaf3c190d1bc36b579029616992057bdfac4e4cf39825819"

      def install
        bin.install "truss-local"
      end
    end
  end

  test do
    system "bin/truss-local", "help"
  end
end
