# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TrussCli < Formula
  desc "CLI to help manage many k8s clusters"
  homepage "https://github.com/get-bridge/truss-cli"
  version "0.2.8"

  depends_on "kubectl"
  depends_on "vault"
  depends_on "sshuttle"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/get-bridge/truss-cli/releases/download/v0.2.8/truss-cli_0.2.8_Darwin_arm64.tar.gz"
      sha256 "17687b54cafa559f9e2fa746c1856eb41423f940a1f4fb647cdf5a8838065db7"

      def install
        bin.install "truss"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/get-bridge/truss-cli/releases/download/v0.2.8/truss-cli_0.2.8_Darwin_x86_64.tar.gz"
      sha256 "3b7774315df21794b6abc77215fbe66e0e9fd1f8995be61eb74fc52a7e6ba96b"

      def install
        bin.install "truss"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/get-bridge/truss-cli/releases/download/v0.2.8/truss-cli_0.2.8_Linux_arm64.tar.gz"
      sha256 "d5f7b772aeb9245e089788ba070286acf172a0ea96532ea31a203e6148a493e2"

      def install
        bin.install "truss"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/get-bridge/truss-cli/releases/download/v0.2.8/truss-cli_0.2.8_Linux_x86_64.tar.gz"
      sha256 "6f78ed8734c38b9e64b6ff38eae2e5207808a332e056273fb5ecfb9965204270"

      def install
        bin.install "truss"
      end
    end
  end

  test do
    system "bin/truss", "help"
  end
end
