# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../download-strategy.rb"
class TrussLocalBeta < Formula
  desc "CLI for running a Local Kubernetes Cluster (beta)"
  homepage "https://github.com/get-bridge/truss-local"
  version "0.7.0-beta.2"

  depends_on "k3d"
  depends_on "pulumi"

  on_macos do
    on_intel do
      url "https://github.com/get-bridge/truss-local/releases/download/v0.7.0-beta.2/truss-local-beta-v0.7.0-beta.2-darwin-amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "5791d6b8b68273dc49d243c2a9a3b3ef6935c43beb8e89e5c0fb210184f0d86f"

      def install
        bin.install "truss-local-beta"
      end
    end
    on_arm do
      url "https://github.com/get-bridge/truss-local/releases/download/v0.7.0-beta.2/truss-local-beta-v0.7.0-beta.2-darwin-arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "3f3dc14b5e6c2c62589762dd28a3f6a48a673337a4c52b8e4c994c244a2b6c44"

      def install
        bin.install "truss-local-beta"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/get-bridge/truss-local/releases/download/v0.7.0-beta.2/truss-local-beta-v0.7.0-beta.2-linux-amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "fbae4196c47dfc61d277a4e6b07e0455035def33beedde6246f70ada1d6b6e63"

        def install
          bin.install "truss-local-beta"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/get-bridge/truss-local/releases/download/v0.7.0-beta.2/truss-local-beta-v0.7.0-beta.2-linux-arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "83bb3e3d94a9369452d11b0fa9978771d852c4272a780801a0c5f77383a3504a"

        def install
          bin.install "truss-local-beta"
        end
      end
    end
  end

  test do
    system "bin/truss-local-beta", "help"
  end
end
