# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../download-strategy.rb"
class TrussLocalBeta < Formula
  desc "CLI for running a Local Kubernetes Cluster (beta)"
  homepage "https://github.com/get-bridge/truss-local"
  version "0.7.0-beta.3"

  depends_on "k3d"
  depends_on "pulumi"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/get-bridge/truss-local/releases/download/v0.7.0-beta.3/truss-local-v0.7.0-beta.3-darwin-amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "79181ce279b8a5dce0caf9e9629342699f8edb978114bb631bf707a238e3bd52"

      define_method(:install) do
        bin.install "truss-local"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/get-bridge/truss-local/releases/download/v0.7.0-beta.3/truss-local-v0.7.0-beta.3-darwin-arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c82703c92cbdb57e32d0e2e3e55c7f9bccec929f4a07c66704576dfc31206d1b"

      define_method(:install) do
        bin.install "truss-local"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/get-bridge/truss-local/releases/download/v0.7.0-beta.3/truss-local-v0.7.0-beta.3-linux-amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "5da310f3b864895fd70dbd3fa5b0a92d16fa9265bc8275d0f430f92ac10cce3a"
      define_method(:install) do
        bin.install "truss-local"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/get-bridge/truss-local/releases/download/v0.7.0-beta.3/truss-local-v0.7.0-beta.3-linux-arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "7845bc85b48d3f9dbec3303b0818f5fe3bbc20681d60c8787edf76f07afffd57"
      define_method(:install) do
        bin.install "truss-local"
      end
    end
  end

  conflicts_with "truss-local"

  test do
    system "bin/truss-local", "help"
  end
end
