# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../download-strategy.rb"
class TrussLocalAT030 < Formula
  desc "CLI for running a Local Kubernetes Cluster"
  homepage "https://github.com/get-bridge/truss-local"
  version "0.3.0"

  depends_on "k3d"
  depends_on "pulumi"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/get-bridge/truss-local/releases/download/v0.3.0/truss-local-v0.3.0-darwin-amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c943fd5d218d52437810447a97a40d9c5bec225ea6e906afbda4b838281a460c"

      def install
        bin.install "truss-local"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/get-bridge/truss-local/releases/download/v0.3.0/truss-local-v0.3.0-darwin-arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "853499c8f867a95411e3df91848d8764a4425bb33eb94b65cbaaeb4be8ac9acc"

      def install
        bin.install "truss-local"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/get-bridge/truss-local/releases/download/v0.3.0/truss-local-v0.3.0-linux-arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "0a4c4bbbce47e4b492c7cb2f544bed37d142e64d58a6de575f97bbad394ad3fe"

      def install
        bin.install "truss-local"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/get-bridge/truss-local/releases/download/v0.3.0/truss-local-v0.3.0-linux-amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "aa69261a1e35bf872f8f43c29d5b601163b501bc84a9b19d78baf7249f80b1bd"

      def install
        bin.install "truss-local"
      end
    end
  end

  test do
    system "bin/truss-local", "help"
  end
end
