# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TrussCli < Formula
  desc "CLI to help manage many k8s clusters"
  homepage "https://github.com/get-bridge/truss-cli"
  version "0.2.9"

  depends_on "kubectl"
  depends_on "vault"
  depends_on "sshuttle"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/get-bridge/truss-cli/releases/download/v0.2.9/truss-cli_0.2.9_Darwin_x86_64.tar.gz"
      sha256 "d5ce9c6d4258a02d8297d438373ab7c0a69ebebf2b447b234790032a7fe11a6f"

      def install
        bin.install "truss"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/get-bridge/truss-cli/releases/download/v0.2.9/truss-cli_0.2.9_Darwin_arm64.tar.gz"
      sha256 "b5ed4f7c00439b13fe80677c3331192fbe2ec6476e5f7f700908f386271f5a23"

      def install
        bin.install "truss"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/get-bridge/truss-cli/releases/download/v0.2.9/truss-cli_0.2.9_Linux_arm64.tar.gz"
      sha256 "22b0f56a5ba2d719958169710d44331c99f780d4ba4255ce4cb0403538b6264c"

      def install
        bin.install "truss"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/get-bridge/truss-cli/releases/download/v0.2.9/truss-cli_0.2.9_Linux_x86_64.tar.gz"
      sha256 "dca5197a13f97fc233d465c5f0d6076d8009e2f9a0f62cd51bc74e060dca21be"

      def install
        bin.install "truss"
      end
    end
  end

  test do
    system "bin/truss", "help"
  end
end
