# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../download-strategy.rb"
class TrussLocal < Formula
  desc "CLI for running a Local Kubernetes Cluster"
  homepage "https://github.com/get-bridge/truss-local"
  version "0.4.0"

  depends_on "k3d"
  depends_on "pulumi"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/get-bridge/truss-local/releases/download/v0.4.0/truss-local-v0.4.0-darwin-arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "0c50e329b565b8c15922c0c841cb5bd996afc665eb2daa33bc3735f1342b6fa7"

      def install
        bin.install "truss-local"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/get-bridge/truss-local/releases/download/v0.4.0/truss-local-v0.4.0-darwin-amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "5c6fc5398be1df941ed4f50418f1f2798fbe11d16289796d76394afa11f64998"

      def install
        bin.install "truss-local"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/get-bridge/truss-local/releases/download/v0.4.0/truss-local-v0.4.0-linux-arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "59d0fdaad3e454e70eae4ba8433da61875a5fbf4f9b76760115e52bf3f536df3"

      def install
        bin.install "truss-local"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/get-bridge/truss-local/releases/download/v0.4.0/truss-local-v0.4.0-linux-amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "fd655f5c52c9f052d4f94d48e111d81aa3f498aaf5ab0afc768dcc68f109d3ec"

      def install
        bin.install "truss-local"
      end
    end
  end

  test do
    system "bin/truss-local", "help"
  end
end
