# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TrussCli < Formula
  desc "CLI to help manage many k8s clusters"
  homepage "https://github.com/get-bridge/truss-cli"
  version "0.2.3"

  if OS.mac?
    url "https://github.com/get-bridge/truss-cli/releases/download/v0.2.3/truss-cli_0.2.3_Darwin_x86_64.tar.gz"
    sha256 "b99a8d43c4f0ed47887e6333f6423dcc83d49283fa20983710c21c623fce5ba1"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/get-bridge/truss-cli/releases/download/v0.2.3/truss-cli_0.2.3_Linux_x86_64.tar.gz"
    sha256 "e885d4a69f3b2138bc8eb4c8b7b3c6303362f27a5f79cfc5580c6de781729e32"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/get-bridge/truss-cli/releases/download/v0.2.3/truss-cli_0.2.3_Linux_arm64.tar.gz"
    sha256 "7ea6f8161346ec0fb207faadbff69c010679c5f84154895baf637da4cb95eb78"
  end

  depends_on "kubectl"
  depends_on "vault"
  depends_on "sshuttle"

  def install
    system "cp", "truss-cli", "truss"
    bin.install "truss"
  end

  test do
    system "bin/truss", "help"
  end
end
